backend:
  name: github
  repo: erenkumcuoglu/erenkumcuoglu
  branch: main

media_folder: images
public_folder: /images

collections:
  - name: posts
    label: Blog Posts
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title,   name: title,   widget: string }
      - { label: Date,    name: date,    widget: datetime }
      - { label: Tag,     name: tag,     widget: string }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Body,    name: body,    widget: markdown }
